apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
<<<<<<< HEAD:deploy/k8s-cbdemo.yaml
        image: harbor.cbksworld.com/tanzu/cbdemo:latest
=======
        image: harbor.cbksworld.com/tanzu/cbdemo
>>>>>>> 26253783794c5e22451f7525c9c3df3d1b834e97:k8s-cbdemo.yaml
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer
